name: Selenium Tests on Ubuntu

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DEV_URL: ${{ vars.DEV_URL }}
      STAG_URL: ${{ vars.STAG_URL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade pytest pytest-html

    - name: Run tests
      run:
        python -m pytest